version: '3.8'

services:
  monitor:
    build:
      context: ./monitor
    container_name: monitor
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  api-server:
    build:
      context: ./api-server
    container_name: api-server
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - monitor
    restart: always

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "5173:5173"
    depends_on:
      - api-server
    restart: always
